type Metric {
  key: String!
  value: Int!
}

input MetricsInput {
  startsAt: Date!
  endsAt: Date!
}

type Query {
  totalSales(input: MetricsInput!): MetricsResult!
  totalOrders(input: MetricsInput!): MetricsResult!
}

type MetricsResult {
  metrics: [Metric!]!
  total: Int!
}
