"""
A payment method is a way to pay for an order in your shop, like credit card, paypal, etc
"""
type PaymentMethod {
  id: ID!
  createdAt: Date!
  updatedAt: Date!

  """
  The payment method's name (e.g. 'Stripe')
  """
  name: String!

  """
  The payment method's icon
  """
  icon: String!

  """
  Whether the payment method is enabled or not
  Not enabled payment methods will not be shown in the storefront
  Useful for payment methods that are not ready to be used yet
  """
  enabled: Boolean!

  """
  Specific data for the payment integration chosen
  Usually, this json stores the payment integration keys
  """
  integrationMetadata: JSON!
}

"""
A payment integration is am integration to be used in a payment method by any shop.
"""
type PaymentIntegration {
  id: ID!
  createdAt: Date!
  updatedAt: Date!

  """
  The payment integration's name (e.g. 'Stripe')
  """
  name: String!

  """
  The payment integration's icon
  """
  icon: String!

  """
  Specific data for the payment integration chosen
  Usually, this json stores the payment integration keys
  """
  metadata: JSON!
}

type Query {
  paymentMethod(id: ID!): PaymentMethod
  paymentMethods: [PaymentMethod!]!
  paymentIntegrations: [PaymentIntegration!]!
}

type Mutation {
  createPaymentMethod(input: CreatePaymentMethodInput!): PaymentMethod!
  updatePaymentMethod(id: ID!, input: UpdatePaymentMethodInput!): PaymentMethod!
  removePaymentMethod(id: ID!): Boolean!
}

input CreatePaymentMethodInput {
  integrationId: ID!
  integrationMetadata: JSON!
  enabled: Boolean
}

input UpdatePaymentMethodInput {
  integrationMetadata: JSON
  enabled: Boolean
}
