type Mutation {
  createProduct(input: CreateProductInput!): ProductResult!
  updateProduct(id: ID!, input: UpdateProductInput!): ProductResult!
  softRemove(id: ID!): ProductResult!
}

" Inputs "
input CreateProductInput {
  name: String!
  description: String
  enabled: Boolean
  archived: Boolean
}

input UpdateProductInput {
  name: String
  description: String
  enabled: Boolean
  archived: Boolean
}

type ProductResult {
  product: Product
  apiErrors: [ProductErrorResult!]!
}

type ProductErrorResult {
  code: ProductErrorCode!
  message: String!
}

enum ProductErrorCode {
  PRODUCT_NOT_FOUND
}
