type Query {
  products(input: ProductListInput): ProductList!
}

input ProductFilters {
  name: StringFilter
  enabled: BooleanFilter
  achived: BooleanFilter
}

type Mutation {
  createProduct(input: CreateProductInput!): Product!
  updateProduct(id: ID!, input: UpdateProductInput!): Product!
  softRemoveProduct(id: ID!): Product!
}

input CreateProductInput {
  name: String!
  description: String
  enabled: Boolean
  archived: Boolean
}

input UpdateProductInput {
  name: String
  description: String
  enabled: Boolean
  archived: Boolean
}
