type Query {
  products(input: ProductListInput): ProductList!
}

type Mutation {
  createProduct(input: CreateProductInput!): Product!
  updateProduct(id: ID!, input: UpdateProductInput!): Product!
  softRemoveProduct(ids: [ID!]!): Boolean!
}

input CreateProductInput {
  name: String!
  description: String
  enabled: Boolean
  archived: Boolean

  assets: [AssetInProductInput!]
}

input UpdateProductInput {
  name: String
  description: String
  enabled: Boolean
  archived: Boolean

  assets: [AssetInProductInput!]
}

input AssetInProductInput {
  id: ID!
  order: Int!
}
