type Shop implements Node {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  """
  The shop's name
  """
  name: String!
  """
  The shop's slug
  """
  slug: String!
  """
  Api key for other stores to connect to this store
  """
  shopApiKey: String!
  """
  Contact email for the shop
  """
  email: String!
  """
  Contact phone number for the shop
  """
  phoneNumber: String!
  """
  The shop's logo
  """
  logo: String
  """
  Physical address of the shop
  """
  address: AddressJson
  """
  The shop's storefront url
  """
  storefrontUrl: String
  """
  The shop's owner
  """
  owner: User!
}

type ShopList implements List {
  items: [Shop!]!
  count: Int!
  pageInfo: PageInfo!
}

type Query {
  shop(slug: String!): Shop
  shops(input: ListInput): ShopList!
}

type Mutation {
  createShop(input: CreateShopInput!): ShopResult!
  updateShop(shopSlug: String!, input: UpdateShopInput!): Shop!
}

input CreateShopInput {
  name: String!
  email: String!
  phoneNumber: String!
  address: CreateAddressInput
  logo: String
  storefrontUrl: String
}

input UpdateShopInput {
  name: String
  email: String
  phoneNumber: String
  address: CreateAddressInput
  logo: String
  storefrontUrl: String
}

type ShopResult {
  shop: Shop
  apiErrors: [ShopErrorResult!]!
}

type ShopErrorResult {
  code: ShopErrorCode!
  message: String!
}

enum ShopErrorCode {
  EMAIL_NOT_VERIFIED
  EMAIL_ALREADY_EXISTS
}
