type User implements Node {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  """
  The user's email (unique)
  """
  email: String!
  """
  Determines if the user's email has been verified
  """
  emailVerified: Boolean!
  """
  The user's shops
  """
  shops: ShopList!
  """
  The user's subscription
  """
  subscription: UserSubscription
}

type UserList implements List {
  items: [User!]!
  count: Int!
  pageInfo: PageInfo!
}

type Query {
  whoami: User
  validateAccessToken: Boolean
}

type Mutation {
  createUser(input: CreateUserInput!): UserResult!
  updateUser(id: ID!, input: UpdateUserInput!): UserResult!
  generateUserAccessToken(input: GenerateUserAccessTokenInput!): UserAccessTokenResult!
  validateOtp(input: ValidateOtpInput!): UserResult!
}

input CreateUserInput {
  email: String!
  password: String!
}

input UpdateUserInput {
  email: String
}

input GenerateUserAccessTokenInput {
  email: String!
  password: String!
}

input ValidateOtpInput {
  otp: String!
}

type UserAccessTokenResult {
  apiErrors: [UserErrorResult!]!
  accessToken: String
}

type UserResult {
  user: User
  apiErrors: [UserErrorResult!]!
}

type UserErrorResult {
  code: UserErrorCode!
  message: String!
}

enum UserErrorCode {
  INVALID_CREDENTIALS
  EMAIL_ALREADY_EXISTS
  PASSWORD_INVALID_LENGTH
  INVALID_EMAIL
  INVALID_OTP
  OTP_EXPIRED
}
