type Mutation {
  createCustomerAddress(input: CreateAddressInput!): AddressResult!
  removeCustomerAddress(addressId: ID!): AddressResult!
  updateCustomerAddress(addressId: ID!, input: UpdateAddressInput!): AddressResult!
}
