"""
A payment method is a way to pay for an order in your shop, like credit card, paypal, etc
"""
type PaymentMethod {
  id: ID!
  createdAt: Date!
  updatedAt: Date!

  """
  The payment method's name (e.g. 'Stripe')
  """
  name: String!

  """
  The payment method's icon
  """
  icon: String
}
