type Address implements Node {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  country: String!
  fullName: String
  streetLine1: String!
  streetLine2: String
  city: String!
  """
  State or region
  """
  province: String!
  postalCode: String!
  phoneNumber: String!
  references: String
  isDefault: Boolean!
}

type AddressList implements List {
  items: [Address!]!
  count: Int!
  pageInfo: PageInfo!
}

type Mutation {
  createCustomerAddress(input: CreateAddressInput!): Address!
  updateCustomerAddress(addressId: ID!, input: UpdateAddressInput!): Address!
  removeCustomerAddress(addressId: ID!): Address!
}

input CreateAddressInput {
  country: String!
  streetLine1: String!
  streetLine2: String
  city: String!
  province: String!
  postalCode: String!
  phoneNumber: String!
  references: String
  isDefault: Boolean
}

input UpdateAddressInput {
  country: String
  streetLine1: String
  streetLine2: String
  city: String
  province: String
  postalCode: String
  phoneNumber: String
  references: String
  isDefault: Boolean
}
