import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

import { ThemeProvider } from '@/lib/shared/components';
import { Notification } from '@/lib/shared/notifications';

import '../globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={inter.className}>
        <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          storageKey="vendyx-marketing-theme"
          disableTransitionOnChange
        >
          <Notification />
          <NextTopLoader color="hsl(var(--primary))" />
          <div className="mx-20">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
